### ISSUE TITLE
Minified script and style

### ISSUE THREAD

**Issue by iannacone** [nk-o/lazy-blocks-custom-control-template#1]
The file script under `assets/js/CONTROL-NAME.min.js` is minified and i do not understand what is for.
Does it should be always added? Is it required?

I notice inside the vars
- `CONTROL_NAME_custom_attribute`
- `CONTROL_NAME `

and the text class `NAMESPACE-lzb-control_CONTROL_NAME`.
So i presume that those names should be replaced, like into the css file `assets/css/CONTROL-NAME.min.css`.
Can you please include the non-minified version of those files also, please?

**Comment by nk-o** [comment]
Look at `/src/` folder https://github.com/nk-o/lazy-blocks-custom-control-template/tree/master/src

`dist` contains a production-ready build.

**Comment by iannacone** [comment]
you are right. thank you! 🙂
